[tools]
elixir = "1.17.3"
erlang = "27.1.2"
go = "1.23.4"
"asdf:chessmango/asdf-flyctl" = "0.3.86"
"sops" = "3.9.3"
"age" = "1.2.1"
"ubi:orhun/git-cliff" = "2.8.0"
"jq" = "1.7.1"

[hooks]
postinstall = "mise run install"

[env]
# _.file = ".env.json"
