{application,styler,
             [{config_mtime,1750345534},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A code-style enforcer that will just FIFY instead of complaining"},
              {modules,['Elixir.Styler','Elixir.Styler.AliasEnv',
                        'Elixir.Styler.Config','Elixir.Styler.Style',
                        'Elixir.Styler.Style.Blocks',
                        'Elixir.Styler.Style.CommentDirectives',
                        'Elixir.Styler.Style.Configs',
                        'Elixir.Styler.Style.Defs',
                        'Elixir.Styler.Style.Deprecations',
                        'Elixir.Styler.Style.ModuleDirectives',
                        'Elixir.Styler.Style.Pipes',
                        'Elixir.Styler.Style.SingleNode',
                        'Elixir.Styler.StyleError','Elixir.Styler.Zipper']},
              {registered,[]},
              {vsn,"1.4.0"}]}.
