name: CLI
on:
  push:
    branches:
      - main
    paths:
      - 'cli/**'
      - '.github/workflows/cli-ci.yml'
      - 'mise.toml'
  pull_request:
    paths:
      - 'cli/**'
      - '.github/workflows/cli-ci.yml'
      - 'mise.toml'

env:
  MISE_EXPERIMENTAL: "1"
  MISE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

jobs:
  cli-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - run: mise run lint/cli

  cli-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - run: mise run test/cli

  cli-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - run: mise run build/cli
      - name: Test CLI binary
        run: cd cli && ./glossia --help