name: Deploy Docs
on:
  push:
    branches:
      - main

env:
  MISE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            docs/node_modules
            docs/.vitepress/cache
            docs/.vitepress/dist
          key: ${{ runner.os }}-pnpm-docs-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-docs-

      - uses: jdx/mise-action@v2

      - name: Install dependencies
        run: pnpm -C docs install

      - name: Build documentation
        run: pnpm -C docs exec vitepress build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: glossia-docs
          directory: docs/.vitepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          deploymentName: Production
