name: Deploy
on:
  push:
    branches:
      - main

env:
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  MISE_GITHUB_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/jdx/mise-action@v3
      - run: mise run deploy
